/**
 * @brief xbox version header
 * @file xbox_version.h
 * @author ouzhiwei
 * @date Wed Dec 10 20:03:35 CST 2025
 * @details
 *
 * @copyright (c) 2025 Intretech Software Development Department. All Rights Reserved.
 *
 * @attention DO NOT EDIT THIS FILE.
 */
#ifndef XBOX_VERSION__H_
#define XBOX_VERSION__H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#define XBOX_VERSION_MAJOR 3
#define XBOX_VERSION_MINOR 1
#define XBOX_VERSION_PATCH 2
#define XBOX_VERSION "v3.1.2"

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* XBOX_VERSION__H_ */
